'use client';

/**
 * StorySection — converts the mobile "share my availabilities to an
 * Instagram / Snapchat story" feature into a landing-page pitch.
 *
 * The mockup on the right is a CSS iPhone frame wrapping a real
 * screenshot of the Opatam-generated story. Two screenshots cycle
 * every STORY_DURATION_MS (Jour ↔ Semaine) with a crossfade and
 * synchronised Instagram-style segmented progress bars, so the
 * visitor sees both formats without scrolling.
 *
 * The Instagram chrome (status bar, segmented progress bars, avatar
 * + handle + ✕, bottom message input + reactions) is overlaid on
 * the screenshot — it reads unambiguously as a vertical story
 * posted to a social network. Snapchat is mentioned in the body
 * copy since the mobile share sheet routes to whichever app the
 * pro picks.
 *
 * Image assets expected at:
 *   /public/instagram-story-jour.png
 *   /public/instagram-story-semaine.png
 * Both should be portrait 9:16 (e.g. 1080×1920) — the actual story
 * content as generated by the mobile app, WITHOUT any Instagram
 * chrome (we add it ourselves).
 */
import { useEffect, useState } from 'react';
import { Instagram, Send } from 'lucide-react';

interface Story {
  label: string;
  src: string;
}

const STORIES: Story[] = [
  { label: 'Jour', src: '/instagram-story-jour.png' },
  { label: 'Semaine', src: '/instagram-story-semaine.png' },
];

/** Each story stays on screen this long before crossfading to the
 *  next. ~5 s is the sweet spot — long enough to read the slot grid
 *  on the screenshot, short enough that the visitor sees BOTH
 *  formats before scrolling past the section. */
const STORY_DURATION_MS = 5000;

export function StorySection() {
  return (
    <section className="relative overflow-hidden bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-950 py-16 sm:py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid lg:grid-cols-12 gap-12 lg:gap-16 items-center">
          {/* ─── Left: heading + 3-step storyline ──────────────────── */}
          <div className="lg:col-span-6 order-2 lg:order-1">
            <div className="inline-flex items-center gap-2 rounded-full bg-primary-100 dark:bg-primary-900/30 px-3 py-1 text-xs font-semibold text-primary-700 dark:text-primary-300 mb-5">
              <Instagram className="w-3.5 h-3.5" />
              Instagram &amp; Snapchat
            </div>
            <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight text-gray-900 dark:text-white leading-tight">
              Une story Instagram. Des créneaux remplis.
              <span className="text-gray-400 dark:text-gray-500"> En 30 secondes.</span>
            </h2>
            <p className="mt-5 text-lg text-gray-600 dark:text-gray-400 max-w-xl">
              Vous avez un trou cet après-midi ? Générez une story avec vos
              dispos et votre QR Code en un tap. Vos abonnées voient, scannent,
              réservent. Compatible Instagram, Snapchat, et tous les réseaux
              à story vertical.
            </p>

            {/* Three numbered beats — same editorial pattern as the
                /nail-artist page. Keeps the copy concrete and
                action-driven. */}
            <ol className="mt-10 space-y-7">
              {[
                { label: '01', body: 'Vous avez un trou ce mardi à 14h.' },
                {
                  label: '02',
                  body:
                    'Tap. Opatam génère votre story avec vos dispos et votre QR Code.',
                },
                {
                  label: '03',
                  body:
                    'Vous publiez sur Instagram. Vos clientes scannent, elles réservent.',
                },
              ].map((step) => (
                <li key={step.label} className="flex gap-5 items-baseline">
                  <span className="text-3xl sm:text-4xl font-light text-gray-300 dark:text-gray-700 tracking-tighter shrink-0 w-12">
                    {step.label}
                  </span>
                  <p className="text-base sm:text-lg text-gray-800 dark:text-gray-200 leading-relaxed">
                    {step.body}
                  </p>
                </li>
              ))}
            </ol>

            {/* Granularity pills — communicates that both single-day
                and weekly views exist without needing a second
                mockup. */}
            <div className="mt-10 flex flex-wrap items-center gap-2.5">
              <span className="text-[10px] sm:text-xs font-semibold uppercase tracking-[0.18em] text-gray-500 dark:text-gray-400">
                Deux formats
              </span>
              <span className="inline-flex items-center gap-1.5 rounded-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 px-3 py-1 text-xs font-medium text-gray-700 dark:text-gray-300">
                Jour
              </span>
              <span className="inline-flex items-center gap-1.5 rounded-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 px-3 py-1 text-xs font-medium text-gray-700 dark:text-gray-300">
                Semaine
              </span>
            </div>
          </div>

          {/* ─── Right: iPhone frame with the Instagram story ──────── */}
          <div className="lg:col-span-6 order-1 lg:order-2 flex justify-center">
            <PhoneStoryMockup />
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─── iPhone + Instagram chrome ────────────────────────────────────
   The screen wraps two crossfading screenshots (Jour / Semaine)
   captured from the actual mobile app. We render Instagram's
   chrome on top — segmented progress bars, profile header, ✕,
   bottom message input + reactions — so the visitor sees a real
   social story, not a UI mockup. */
function PhoneStoryMockup() {
  const [active, setActive] = useState(0);

  // Auto-advance cycle. The interval is the single source of truth
  // for both the story switch and the progress-bar animation —
  // both use STORY_DURATION_MS so they stay in sync visually.
  useEffect(() => {
    const id = window.setInterval(() => {
      setActive((idx) => (idx + 1) % STORIES.length);
    }, STORY_DURATION_MS);
    return () => window.clearInterval(id);
  }, []);

  return (
    <div className="relative">
      {/* iPhone outer frame */}
      <div className="relative w-[280px] sm:w-[300px] h-[560px] sm:h-[600px] rounded-[40px] bg-gray-900 p-[6px] shadow-2xl shadow-black/40 ring-1 ring-black/20">
        {/* Screen */}
        <div className="relative w-full h-full rounded-[34px] overflow-hidden bg-gray-950">
          {/* Crossfading story screenshots (the actual content). Both
              images are stacked; opacity flips based on `active`.
              `transition-opacity` keeps the crossfade smooth. */}
          {STORIES.map((story, idx) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={story.src}
              src={story.src}
              alt={`Story ${story.label} — Opatam`}
              className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-700 ${
                active === idx ? 'opacity-100' : 'opacity-0'
              }`}
            />
          ))}

          {/* Notch */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-32 h-7 bg-black rounded-b-2xl z-30" />

          {/* ── Status bar (time + bars + battery) ── */}
          <div className="absolute top-0 inset-x-0 flex items-center justify-between px-6 pt-2 text-white text-xs font-medium z-20 drop-shadow-md">
            <span>9:41</span>
            <span className="flex items-center gap-1">
              <span>•••</span>
              <span>📶</span>
              <span>100%</span>
            </span>
          </div>

          {/* ── Instagram story progress bars (one per story). Each bar
                fills over STORY_DURATION_MS while its story is active
                and snaps back to empty when another story becomes
                active. ── */}
          <div className="absolute top-10 inset-x-0 px-4 flex gap-1 z-20">
            {STORIES.map((story, idx) => {
              const isActive = active === idx;
              return (
                <div
                  key={story.src}
                  className="flex-1 h-0.5 bg-white/30 rounded-full overflow-hidden"
                >
                  <div
                    className="h-full bg-white rounded-full"
                    style={{
                      width: isActive ? '100%' : '0%',
                      transitionProperty: 'width',
                      transitionDuration: isActive ? `${STORY_DURATION_MS}ms` : '0ms',
                      transitionTimingFunction: 'linear',
                    }}
                  />
                </div>
              );
            })}
          </div>

          {/* ── Instagram bottom bar: message input + heart + send ── */}
          <div className="absolute bottom-0 inset-x-0 px-3 pb-4 pt-3 z-20 bg-gradient-to-t from-black/50 to-transparent">
            <div className="flex items-center gap-2">
              <div className="flex-1 rounded-full border border-white/60 px-3.5 py-2 text-[11px] text-white/90">
                Envoyer un message...
              </div>
              <span className="text-white text-lg leading-none">♥</span>
              <Send className="w-4 h-4 text-white" strokeWidth={2} aria-hidden="true" />
            </div>
          </div>
        </div>
      </div>

      {/* "Jour / Semaine" indicator under the phone — mirrors the
          progress bar above so a static viewer (e.g. someone with
          reduced-motion enabled) still understands two stories are
          rotating. */}
      <div className="mt-5 flex items-center justify-center gap-2 text-xs">
        {STORIES.map((story, idx) => (
          <span
            key={story.src}
            className={`inline-flex items-center px-3 py-1 rounded-full border transition-colors ${
              active === idx
                ? 'bg-primary-600 border-primary-600 text-white font-medium'
                : 'bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400'
            }`}
          >
            {story.label}
          </span>
        ))}
      </div>
    </div>
  );
}

